# Change these first
owner: cardano-foundation
repo: cf-summit-evoting-status

sites:
  - name: voting.summit.cardano.org
    url: https://voting.summit.cardano.org/
    maxResponseTime: 2000
    __dangerous__body_down_if_text_missing: 'Cardano Ballot - Cardano Summit Awards Voting'
    expectedStatusCodes:
      - 200
  - name: event-api
    url: https://follower-api.voting.summit.cardano.org/api/reference/event/CARDANO_SUMMIT_AWARDS_2024
    maxResponseTime: 2000
    __dangerous__body_down_if_text_missing: 'TEST_2024'
    expectedStatusCodes:
      - 200
  - name: user-verification-api
    url: https://user-verification.voting.summit.cardano.org/api/sms/user-verification/start-verification
    maxResponseTime: 2000
    expectedStatusCodes:
      - 405
  - name: blockchain-follower-api
    url: https://follower-api.voting.summit.cardano.org/api/blockchain/tip
    maxResponseTime: 2000
    __dangerous__body_down_if_text_missing: '"synced":true'
    expectedStatusCodes:
      - 200
  - name: login-api
    url: http://api.voting.summit.cardano.org/api/auth/login
    maxResponseTime: 2000
    __dangerous__body_down_if_text_missing: 'Full authentication is required to access this resource'
    expectedStatusCodes:
      - 401
  - name: cast-vote-api
    url: http://api.voting.summit.cardano.org/api/vote/cast
    maxResponseTime: 2000
    __dangerous__body_down_if_text_missing: 'Full authentication is required to access this resource'
    expectedStatusCodes:
      - 401
  - name: get-votes-api
    url: http://api.voting.summit.cardano.org/api/vote/votes/CARDANO_SUMMIT_AWARDS_2024
    maxResponseTime: 2000
    __dangerous__body_down_if_text_missing: 'Full authentication is required to access this resource'
    expectedStatusCodes:
      - 401
  - name: get-vote-receipt-api
    url: http://api.voting.summit.cardano.org/api/vote/receipt/CARDANO_SUMMIT_AWARDS_2024/AMBASSADOR
    maxResponseTime: 2000
    __dangerous__body_down_if_text_missing: 'Full authentication is required to access this resource'
    expectedStatusCodes:
      - 401
  - name: keria
    url: http://keria.voting.summit.cardano.org
    maxResponseTime: 2000
    expectedStatusCodes:
      - 401
  - name: keria-provisioning
    url: https://keria-provisioning.voting.summit.cardano.org/api/v1/provision
    maxResponseTime: 2000
    __dangerous__body_down_if_text_missing: 'Method Not Allowed'
    expectedStatusCodes:
      - 405

  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  cname: status2024.voting.summit.cardano.org
  #baseUrl: /
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: cf-summit-evoting-status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO


